// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owwelcertfugvndghwkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93d2VsY2VydGZ1Z3ZuZGdod2tsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjUyNDAsImV4cCI6MjA2NzIwMTI0MH0.E41p9e618WwOezLWkFiPw4i4yiqJ8DAfLz8SLV7E2RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});