// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyrbzvsymcmzsesbnnms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cmJ6dnN5bWNtenNlc2Jubm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTQwMjUsImV4cCI6MjA2NzE3MDAyNX0.Tmq65O_eet_oOUnD4vYCCnUx4Kpo7ci87VmyYengZ08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});